name: Build and Commit GeoData

on:
  schedule:
    - cron: '0 3 */2 * *'
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build geo files
        run: |
          go mod tidy
          go run main.go

      - name: Commit and push geodata files to main branch
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add geosite.dat geoip.dat
          git commit -m "auto: update geodata files [skip ci]" || echo "No changes to commit"
          git push
